stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    - utils/custom_logging.py
    - utils/utils_data_ingestion.py
    - params.yaml
    params:
    - data_ingestion.test_size
    outs:
    - data/raw