stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    - utils/custom_logging.py
    - utils/utils_data_ingestion.py
    - params.yaml
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    - utils/custom_logging.py
    - utils/utils_data_preprocessing.py
    - params.yaml
    outs:
    - data/processed

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/processed
    - src/features/feature_engineering.py
    - utils/custom_logging.py
    - utils/utils_feature_engineering.py
    - params.yaml
    params:
    - feature_engineering.max_features
    outs:
    - data/interim

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/interim/train_tfidf.csv
    - src/model/model_building.py
    - utils/custom_logging.py
    - utils/utils_model_building.py
    - params.yaml
    params:
    - model_building.n_estimators
    - model_building.learning_rate
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/model.pkl
    - data/interim/test_tfidf.csv
    - utils/custom_logging.py
    - utils/utils_model_evaluation.py
    - src/model/model_evaluation.py
    metrics:
    - reports/metrics.json
